---
title: "DS2003 Midterm Dataset Selection"
author: "Andrew Holzwarth, Dylan Cole, Lexi Van Metre, Carson Crenshaw"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Dataset Selection will is due Wednesday night on Canvas. 
Original Dataset Link: https://www.advancedsportsanalytics.com/nba-raw-data

```{r}
library(dplyr)
library(ggplot2)
library(plotly)
library(tidyverse)
```

```{r}
#Question 1
  #Is there a trend between team efg percentage and offensive rating by team?

#Question 2
  #Is there a trend between team_ft_rate (which we are using to track fouls), and total score, sorted by team and season
```

```{r}
# Load in our data
nbadata <- read.csv("/Users/andrewholzwarth/Desktop/DS 2003/Midterm Project/ASA Heat Check Data (2) copy.csv")
```

```{r}
# Data Wrangling

#Remove unnecessary variables
nbadata_wrangled <- nbadata[,c(1:12,62)]

# Isolate unique game values (each game_id has 2 values, 1 for each team)
nbaunique <- nbadata_wrangled[!duplicated(nbadata_wrangled[ , c(1, 5)]), ]


#Clean up data (make all lowercase), aesthetics
names(nbaunique) <- tolower(names(nbaunique))
nbaunique

# Make factor variables
nbaunique$h_a <- as.factor(nbaunique$h_a)
nbaunique$ot <- as.factor(nbaunique$ot)
nbaunique$team_abbrev <- as.factor(nbaunique$team_abbrev)
nbaunique$season <- as.factor(nbaunique$season)
```

```{r}
#Andrew's test area

nba_average <- nbaunique %>%
  group_by(team_abbrev, season) %>%
  summarize(team_score = mean(team_score),
            team_pace = mean(team_pace),
            team_efg_pct = mean(team_efg_pct),
            team_tov_pct = mean(team_tov_pct),
            team_orb_pct = mean(team_orb_pct),
            team_ft_rate = mean(team_ft_rate),
            team_off_rtg = mean(team_off_rtg))
nba_average
```


```{r}
# Create Graphs

question_1_plot <- ggplot(nba_average, aes(x = team_efg_pct, y = team_off_rtg, color = team_abbrev, shape = season))+
  geom_point()+
  theme_bw()

question_1_plot


question_2_plot <- ggplot(nba_average, aes(x = team_ft_rate, y = team_score, color = team_abbrev, shape = season))+
  geom_point()+
  theme_bw()

question_2_plot
```

